name: release

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:

env:
  IMAGE: polprzewodnikowy/n64sdkmod

jobs:
  merged:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-20.04

    steps:
      - name: get date
        id: date
        run: echo "::set-output name=date::$(date +'%Y.%m.%d-%H_%M_%S')"

      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.date.outputs.date }}
          release_name: v${{ steps.date.outputs.date }}

      - name: get image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE }}

      - name: log in to the repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags:
            - ${{ env.IMAGE }}:latest
            - ${{ env.IMAGE }}:v${{ steps.date.outputs.date }}
          labels: ${{ steps.meta.outputs.labels }}
