name: release

on:
  pull_request:
    branches:
      - master
    types:
      - closed
  workflow_dispatch:

env:
  IMAGE: polprzewodnikowy/n64sdkmod

jobs:
  merged:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-20.04

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: master

      - name: get date
        id: date
        run: echo "::set-output name=date::$(date --utc +'%Y.%m.%d-%H%M%S')"

      - name: get commit info
        id: commit
        shell: bash
        run: |
          echo "::set-output name=sha::$(git rev-parse HEAD)"
          echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"

      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.date.outputs.date }}
          release_name: ${{ steps.date.outputs.date }}

      - name: get image metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE }}

      - name: log in to the repository
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}:latest,${{ env.IMAGE }}:${{ steps.date.outputs.date }},${{ env.IMAGE }}:${{ steps.commit.sha }},${{ env.IMAGE }}:${{ steps.commit.short_sha }}
          labels: ${{ steps.meta.outputs.labels }}
